# Generated by Django 4.0.5 on 2024-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('oneline', models.TextField(blank=True)),
                ('stars', models.CharField(max_length=250)),
                ('votes', models.IntegerField(default=0)),
                ('runtime', models.FloatField()),
                ('gross', models.FloatField(default=0)),
            ],
        ),
    ]
